### ISSUE TITLE
Add DKIM support

### ISSUE THREAD

**Issue by ricick** [joelcox/codeigniter-amazon-ses#19]
It would be awesome if this library did DKIM signing for you.

**Comment by joelcox** [comment]
Hi Ricick,

I've looked into this before and decided against this since it would require a major overhaul of the library. Amazon SES allows you to compose messages using their proprietary API or by sending a RAW email (just like your email client would send them). Currently, this library uses Amazon's proprietary way of doing things. 

DKIM support for their own API [is high on their priority list](https://forums.aws.amazon.com/message.jspa?messageID=292230#292230) and will be integrated with the library when it becomes available. I'll put this issue on hold for now. Thanks for your input!

**Comment by joelcox** [comment]
You can now sign your emails using Amazon SES' Easy DKIM feature!

http://aws.amazon.com/about-aws/whats-new/2012/07/17/easily-dkim-sign-your-emails-with-amazon-ses/
